blank_issues_enabled: false
contact_links:
  - name:  GitHub Discussions
    url: https://github.com/epti-dev/bc-fastapi/discussions
    about: Para preguntas generales, ideas o discusiones usa Discussions
  - name:  Documentaci贸n FastAPI
    url: https://fastapi.tiangolo.com/
    about: Consulta la documentaci贸n oficial de FastAPI
  - name:  Documentaci贸n Pydantic
    url: https://docs.pydantic.dev/
    about: Consulta la documentaci贸n oficial de Pydantic
