[project]
name = "catalogo-productos"
version = "1.0.0"
description = "API de CatÃ¡logo de Productos"
requires-python = ">=3.13"
dependencies = [
    "fastapi>=0.115.0",
    "uvicorn[standard]>=0.32.0",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
